global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "student-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["student-backend:5000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
