apiVersion: v1
kind: Service
metadata:
  name: student-backend-service
spec:
  type: NodePort
  selector:
    app: student-backend
  ports:
    - port: 5000        # service port
      targetPort: 5000  # container port
      nodePort: 30001   # external port
